version: "3.9"
services:
  zeek:
    image: custom-zeek
    network_mode: host
    #command: ["-i", "br_icsnet", "local", "custom-scripts/"]
    volumes:
      - ./zeek-scripts:/usr/local/zeek/share/zeek/site/scripts
      - ./zeek-logs:/pcap
      - shared-data:/data
    command: /bin/sh -c '/usr/local/bin/check-and-flag.sh & exec zeek -i br_icsnet local custom-scripts/'

  audio1:
    build: audio-docker/.
    privileged: true
    working_dir: /src
    entrypoint: ["python3", "server2.py"]
    container_name: audio1
    volumes:
      - ../src:/src
      - shared-data:/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      fnet:
        ipv4_address: 192.168.1.35

  pys:
    build: ics-docker/.
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "FactorySimulation.py"]
    container_name: pys
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      fnet:
        ipv4_address: 192.168.1.31
      
  plc1:
    build: ics-docker/.
    privileged: true 
    working_dir: /src
    entrypoint: ["./start.sh", "PLC1.py"]
    container_name: plc1
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.12
      fnet:
        ipv4_address: 192.168.1.12

      
 #plc2:
  #  build: ics-docker/.
    #stdin_open: true # docker run -i
    #tty: true
    #privileged: true
    #working_dir: /src
    #entrypoint: ["./start.sh", "PLC2.py"]
    #container_name: plc2
    #volumes:
    #  - ../src:/src
    #  - "/etc/timezone:/etc/timezone:ro"
    #  - "/etc/localtime:/etc/localtime:ro"
    #networks:
    #  wnet:
    #    ipv4_address: 192.168.0.12
    #  fnet:
    #    ipv4_address: 192.168.1.12

  plc3:
    build: ics-docker/.
    #stdin_open: true # docker run -i
    #tty: true
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "PLC3.py"]
    container_name: plc3
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.11
      fnet:
        ipv4_address: 192.168.1.11
    ports:
      - "12345:12345"  # Map host port 8080 to container port 80

      
  hmi1:
    build: ics-docker/.
    stdin_open: true # docker run -i
    tty: true  
    working_dir: /src
    privileged: true
    entrypoint: ["./start.sh", "HMI1.py"]
    container_name: hmi1
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.21
        
  hmi2:
    build: ics-docker/.
    stdin_open: true # docker run -i
    tty: true 
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "HMI2.py"]
    container_name: hmi2
    volumes:
      - ../src:/src
    networks:
      wnet:
        ipv4_address: 192.168.0.22
              
        
  attacker:
    build: attacker-docker/.
    stdin_open: true # docker run -i
    privileged: true
    tty: true
    working_dir: /src
    entrypoint: ["./start.sh", "Attacker.py"]
    container_name: attacker
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      
    networks:
      wnet:
        ipv4_address: 192.168.0.42

volumes:
  zeek-logs: {} 
  shared-data:
    driver: local  # Using the local driver for simplicity
       
      
networks:
  wnet:
    driver: bridge
    name: icsnet
    ipam:
     config:
       - subnet: 192.168.0.0/24
         gateway: 192.168.0.1
    driver_opts:
      com.docker.network.bridge.name: br_icsnet
  fnet:
    driver: bridge
    name: phynet
    ipam:
     config:
       - subnet: 192.168.1.0/24
         gateway: 192.168.1.1 
    driver_opts:
      com.docker.network.bridge.name: br_phynet


